### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by Vyloo** [overextended/oxmysql#95] opened 2022-03-02 14:16 UTC
I am using the latest release
 I have referenced previously reported issues
 I have referenced available documentation and cannot resolve the issue
 I'm certain this is an issue with oxymysql, and not with my resource

For whatever reason, in the console, it’s telling me it’s connecting to 192.168.3.103 but in the config file, I have it set for 192.168.3.122.

It’s not seeing the 192.168.3.122, my MySQL is separated from the fivem server.

![image](https://user-images.githubusercontent.com/62805463/156378803-8c76392c-2513-41e1-aa86-67aca8026f56.png)

![image](https://user-images.githubusercontent.com/62805463/156378832-e9cbcfdb-6a5c-44a8-ae4e-2b4e9cb8a3b9.png)

**Comment by Zaickz** [comment] 2022-03-02 19:49
Do you use certain special characters in your password?

**Comment by thelindat** [comment] 2022-03-02 22:09
These IP discrepancies have always been the result of containers like Pterodactyl.

**Comment by darksaid98** [comment] 2022-03-05 12:10
This seems like a duplicate of #83. 

The wrong IP being thrown in the error makes people assume that it's the problem. It's not. If the address wasn't valid another error would have been thrown.

The username or password is incorrect. I suspect special characters in the password to be the culprit (as per usual at this point). Try this version of `mysql_connection_string`.

```
set mysql_connection_string "user=DBUSERNAME;database=DBNAME;password=DBPASSWORD;ip=DBIP;charset=utf8mb4"
```

**Comment by mat945** [comment] 2022-03-07 15:17
Hey, i got the same problem, did someone know how to fix it ? mysql connection string is good, script is perfectly installed, i don't know how to fix that

**Comment by Vyloo** [comment] 2022-03-07 17:32
> These IP discrepancies have always been the result of containers like Pterodactyl.

This is true.

**Closed** 2022-03-08 02:31 UTC
Labels: bug, question, investigating
