### ISSUE TITLE
oxmysql: TypeError: val.slice is not a function

### ISSUE THREAD

**Issue by vietgamingnetwork** [overextended/oxmysql#171] opened 2023-03-16 03:12 UTC
## Issue checklist

- [ x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
[script:oxmysql] Error calling system tick function in resource oxmysql: TypeError: val.slice is not a function
[      script:oxmysql] stack:
[      script:oxmysql] TypeError: val.slice is not a function
[      script:oxmysql]     at escapeString (@oxmysql/dist/build.js:196:27)
[      script:oxmysql]     at Object.escape (@oxmysql/dist/build.js:86:18)
[      script:oxmysql]     at Object.format (@oxmysql/dist/build.js:118:85)
[      script:oxmysql]     at PoolConnection.format (@oxmysql/dist/build.js:14269:26)
[      script:oxmysql]     at PoolConnection.query (@oxmysql/dist/build.js:14292:29)
[      script:oxmysql]     at @oxmysql/dist/build.js:14801:18
[      script:oxmysql]     at @oxmysql/dist/build.js:14707:42
[      script:oxmysql]     at processTicksAndRejections (node:internal/process/task_queues:78:11)
[      script:oxmysql]     at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:65:3)
[      script:oxmysql]     at onTick (citizen:/scripting/v8/timer.js:227:28)

**Code**
```lua
    local userId = exports.oxmysql:insert_async('INSERT INTO users (identifier, name, status, items, metadata, character , phone, contacts) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ', {
		iCore.players[id].identifier, iCore.players[id].name, json.encode(iCore.players[id].status), json.encode(iCore.players[id].items), json.encode(iCore.players[id].metadata), json.encode(iCore.players[id].character), json.encode(iCore.players[id].phone), json.encode(iCore.players[id].contacts)
	})
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact: latest
- Operating system: linux

**Database details**
- MariaDB

**Comment by darksaid98** [comment] 2023-03-22 12:25
Closing since you said the issue was resolved and the cause was user input. Hopefully this will be a good reference for other people running into the same error `TypeError: val.slice is not a function` ^_^.

**Closed by darksaid98** 2023-03-22 12:25 UTC
Labels: wontfix
