### ISSUE TITLE
Unable t establish a connection to the database

### ISSUE THREAD

**Issue by ARSSANTO** [overextended/oxmysql#91] opened 2022-02-25 05:02 UTC
- [ YES] I am using the latest release
- [ ] I have referenced previously reported issues
- [ YES] I have referenced available documentation and cannot resolve the issue
- [ YES] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
EVERY THING working fine data saving every thing but but but this error comes up on console 

**Screenshots**
![Capturesda](https://user-images.githubusercontent.com/55808925/155656631-fcbddd0a-35c1-47e9-835e-47e7f7acd375.PNG)

**Server details**
- FXServer artifact 5181
- Winodws 10

**Comment by ProSlayz** [comment] 2022-02-25 06:40
j ai la meme erreur en local sa marche je mes sa sur un hebergeur impossible de se connecter a la basse de donné

**Comment by ARSSANTO** [comment] 2022-02-25 07:47
Fact is Data saving with 80+ player database

**Comment by LukeWasTakenn** [comment] 2022-02-25 14:05
Duplicate of #88

**Closed by LukeWasTakenn** 2022-02-25 14:05 UTC
Labels: bug

**Comment by IMTR0J4N** [comment] 2022-06-23 10:36
L'erreur doit sûrement venir de ton URI de connexion : Ton mot de passe doit contenir des caractères comme . / ? ! . 
Si c'est le cas change ton mot de passe et tout fonctionnera
