### ISSUE TITLE
Never had an issue before hand..

### ISSUE THREAD

**Issue by TheRealDigee** [overextended/oxmysql#155] opened 2022-11-14 21:52 UTC
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
When I swap the oxmysql files, as I normally do every so often when there is an update, I never have an issue, it's always simple drag and drop. Oxmysql starts before anything that uses it & it seems to be happening with the Codesign scripts. Unable to return query oxmysql. Sometimes it throws a random mysql-async error as well. None of this was happening prior to the oxmysql swap.

**Screenshots**
[38;5;91m[     script:cd_radar] [Codesign ErrorHandler] - table expected, got nil : nil
[     script:cd_radar] [cd_radar] [error_code-468454] - Please read our documentation website [https://docs.codesign.pro] and make efforts to resolve issues yourself. Only contact the Codesign team as a last resort.
[     script:cd_radar] [cd_radar] - Saved all cached data.
[    script:cd_garage] [Codesign ErrorHandler] - table expected, got nil : nil
[    script:cd_garage] [cd_garage] [error_code-468454] - Please read our documentation website [https://docs.codesign.pro] and make efforts to resolve issues yourself. Only contact the Codesign team as a last resort.
[    script:cd_garage] [Codesign ErrorHandler] - @mysql-async/lib/MySQL.lua:88: No such export query in resource oxmysql
[    script:cd_garage] [cd_garage] [error_code-99999999 ^] - Please read our documentation website [https://docs.codesign.pro] and make efforts to resolve issues yourself. Only contact the Codesign team as a last resort.
[    script:cd_garage] [Codesign ErrorHandler] - table expected, got nil : nil
[    script:cd_garage] [cd_garage] [error_code-46584645] - Please read our documentation website [https://docs.codesign.pro] and make efforts to resolve issues yourself. Only contact the Codesign team as a last resort.
[    script:cd_garage] [Codesign ErrorHandler] - @mysql-async/lib/MySQL.lua:88: No such export query in resource oxmysql
[    script:cd_garage] [cd_garage] [error_code-99999999 ^] - Please read our documentation website [https://docs.codesign.pro] and make efforts to resolve issues yourself. Only contact the Codesign team as a last resort.
[ script:loaf_housing] SCRIPT ERROR: @mysql-async/lib/MySQL.lua:88: No such export query in resource oxmysql
[38;5;69m[ script:loaf_housing] [INFO] Checking rent
[ script:loaf_housing] SCRIPT ERROR: @mysql-async/lib/MySQL.lua:88: No such export query in resource oxmysql
[    script:cd_garage] [Codesign ErrorHandler] - table expected, got nil : nil
[    script:cd_garage] [cd_garage] [error_code-5454] - Please read our documentation website [https://docs.codesign.pro] and make efforts to resolve issues yourself. Only contact the Codesign team as a last resort.
[    script:cd_garage] [Codesign ErrorHandler] - @mysql-async/lib/MySQL.lua:88: No such export query in resource oxmysql
[    script:cd_garage] [cd_garage] [error_code-99999999 ^] - Please read our documentation website [https://docs.codesign.pro] and make efforts to resolve issues yourself. Only contact the Codesign team as a last resort.
[    script:cd_garage] [0m[Codesign ErrorHandler] - table expected, got nil : nil
[    script:cd_garage] [cd_garage] [error_code-3122] - Please read our documentation website [https://docs.codesign.pro] and make efforts to resolve issues yourself. Only contact the Codesign team as a last resort.
[    script:cd_garage] [cd_garage] - Saved all cached data.
[script:t1ger_dealers] [SAVED] DISPLAY VEHICLES
[script:t1ger_dealers] [ERROR] - Cache table for dealer [1] at display spot [1] is empty
[script:t1ger_dealers] [ERROR] - Cache table for dealer [1] at display spot [2] is empty
[script:t1ger_dealers] [ERROR] - Cache table for dealer [1] at display spot [3] is empty
[script:t1ger_dealers] [ERROR] - Cache table for dealer [1] at display spot [4] is empty
[script:t1ger_dealers] [ERROR] - Cache table for dealer [1] at display spot [5] is empty
[script:t1ger_dealers] [ERROR] - Cache table for dealer [1] at display spot [6] is empty
[script:t1ger_traffic] [SAVED ANPR] All Rows> txaEvent "serverShuttingDown" "{＂delay＂:5000,＂author＂:＂Digee＂,＂message＂:＂Server restarting (requested by Digee).＂}"
Server shutdown imminent. Kicking all players.

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**
I expected it to be the same as any other update, simply drag and drop. Now it's breaking most if not all of the Codesign Scripts from pulling the proper data.

**Additional context**
Seems to only be happening with the Codesign Scripts, doesn't seem to be breaking anything else.

**Server details**
- 5971
- Windows 10 Professional

**Database details**
-  MySQL
- Legacy

**Comment by TheRealDigee** [comment] 2022-11-14 21:53
I have also modified the CD Scripts FXmanifest LUA as well as their configs to utilize oxmysql as they were just utilizing mysql prior~ If anything changing it made the problems worse.

**Comment by TheRealDigee** [comment] 2022-11-14 21:55
Nevermind all of this, very dumb fix on oxmysql side.

**Comment by thelindat** [comment] 2022-11-14 21:59
Those checkboxes are there for a reason,  it to just fill in with x.

Duplicate of https://github.com/overextended/oxmysql/issues/154 https://github.com/overextended/oxmysql/issues/151 https://github.com/overextended/oxmysql/issues/146 https://github.com/overextended/oxmysql/issues/142 https://github.com/overextended/oxmysql/issues/136

**Closed by thelindat** 2022-11-14 21:59 UTC
Labels: bug
